
#ifndef PORT_CFG_H
#define PORT_CFG_H

// Configs for LED1
#define PORT_PIN_LED1_Index PortF_PIN3
#define PORT_PIN_LED1_DIRECTION (Port_PinDirectionType) PORT_PIN_OUT
#define PORT_PIN_LED1_ID PortF_PIN3
#define PORT_PIN_LED1_INITIAL_MODE (Port_PinModeType) PORT_PIN_MODE_DIO
#define PORT_PIN_LED1_LEVEL_VALUE (Port_PinLevelType) PORT_PIN_LEVEL_LOW
#define PORT_PIN_LED1_INTERNAL_RESISTOR (Port_InternalResistorType) PORT_RESISTOR_PULL_UP

typedef enum
{
    PortA_PIN0,
    PortA_PIN1,
    PortA_PIN2,
    PortA_PIN3,
    PortA_PIN4,
    PortA_PIN5,
    PortA_PIN6,
    PortA_PIN7,
    PortB_PIN0,
    PortB_PIN1,
    PortB_PIN2,
    PortB_PIN3,
    PortB_PIN4,
    PortB_PIN5,
    PortB_PIN6,
    PortB_PIN7,
    PortC_PIN0,
    PortC_PIN1,
    PortC_PIN2,
    PortC_PIN3,
    PortC_PIN4,
    PortC_PIN5,
    PortC_PIN6,
    PortC_PIN7,
    PortD_PIN0,
    PortD_PIN1,
    PortD_PIN2,
    PortD_PIN3,
    PortD_PIN4,
    PortD_PIN5,
    PortD_PIN6,
    PortD_PIN7,
    PortE_PIN0,
    PortE_PIN1,
    PortE_PIN2,
    PortE_PIN3,
    PortE_PIN4,
    PortE_PIN5,
    PortE_PIN6,
    PortE_PIN7,
    PortF_PIN0,
    PortF_PIN1,
    PortF_PIN2,
    PortF_PIN3,
    PortF_PIN4,
    PortF_PIN5,
    PortF_PIN6,
    PortF_PIN7,
    PortG_PIN0,
    PortG_PIN1,
    PortG_PIN2,
    PortG_PIN3,
    PortG_PIN4,
    PortG_PIN5,
    PortG_PIN6,
    PortG_PIN7,
    PortH_PIN0,
    PortH_PIN1,
    PortH_PIN2,
    PortH_PIN3,
    PortH_PIN4,
    PortH_PIN5,
    PortH_PIN6,
    PortH_PIN7,
    PortI_PIN0,
    PortI_PIN1,
    PortI_PIN2,
    PortI_PIN3,
    PortI_PIN4,
    PortI_PIN5,
    PortI_PIN6,
    PortI_PIN7,
    PortJ_PIN0,
    PortJ_PIN1,
    PortJ_PIN2,
    PortJ_PIN3,
    PortJ_PIN4,
    PortJ_PIN5,
    PortJ_PIN6,
    PortJ_PIN7,
    PortK_PIN0,
    PortK_PIN1,
    PortK_PIN2,
    PortK_PIN3,
    PortK_PIN4,
    PortK_PIN5,
    PortK_PIN6,
    PortK_PIN7,
    Port_PIN_NUM
} Port_PinType;

#endif /* PORT_CFG_H */